version: 2.1
workflows:
  main:
    jobs:
      - build

job-references:
  node_env: &node_env
    docker:
      - image: circleci/node:latest
  restore_npm: &restore_npm
    keys:
      - node-v1-{{ checksum "package.json" }}
      - node-v1-

  install_npm: &install_npm
    name: "Install NPM dependencies"
    command: npm ci

  save_npm: &save_npm
    key: node-v1-{{ checksum "package.json" }}
    paths:
       node_modules

jobs:
  build:
    <<: *node_env
    steps:
      - checkout
      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm
      - run:
          name: "Build"
          command: |
            cd assets/dev
            npm run build:prod
      - run:
          name: "Check artifacts commited to repo"
          command: "[ -z \"$(git status --porcelain)\" ]"
